version: 4.21.0-{branch}-{build}
image: Ubuntu2004
clone_depth: 1
cache:
  - /home/appveyor/.ccache

build_script:
- sh: >-
    git log > /tmp/gitlog.txt

    grep -q '\[ci reset\]' /tmp/gitlog.txt && rm -rf /home/appveyor/.ccache

    sudo apt-get update -qq

    sudo apt-get install -qq wget

    sudo wget https://raw.githubusercontent.com/fluxer/katana-ubuntu/master/katana.list -O /etc/apt/sources.list.d/katana.list

    sudo apt-get update -qq

    sudo apt-get install -qq cmake katie-dev katanalibs \
        katana-baseapps xorg-dev libqalculate-dev libxxf86vm-dev \
        libx11-xcb-dev libxcb-composite0-dev libxcb-damage0-dev \
        libxcb-xfixes0-dev libxcb-render0-dev libxcb-randr0-dev libxcb-shape0-dev \
        libxcb-sync-dev libxcb-render-util0-dev libxcb-keysyms1-dev \
        libglu1-mesa-dev mesa-common-dev libmtp-dev libusb-1.0-0-dev libssh-dev \
        libsmbclient-dev libdrm-dev libraw1394-dev libsensors4-dev \
        libegl-dev libpci-dev libopenexr-dev liblzma-dev libbz2-dev libgphoto2-dev \
        liblightdm-gobject-1-dev libkmod-dev libdbusmenu-katie ccache

    export PATH="/usr/lib/ccache/:$PATH"

    mkdir build

    cd build

    cmake ../ -Wno-dev

    make -j $(nproc || echo 1)
